[versions]
agp = "8.2.2"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
lifecycleVersion = "2.7.0"
room = "2.6.1"
coroutines = "1.7.3"
navigation = "2.7.6"
workmanager = "2.9.0"
datastore = "1.1.0"
constraintlayout = "2.1.4"
gson = "2.10.1"
junit = "4.13.2"
androidxJunit = "1.1.5"
espresso = "3.5.1"

[libraries]
core-ktx                = { group = "androidx.core",                    name = "core-ktx",                    version.ref = "coreKtx" }
appcompat               = { group = "androidx.appcompat",               name = "appcompat",                   version.ref = "appcompat" }
material                = { group = "com.google.android.material",      name = "material",                    version.ref = "material" }
constraintlayout        = { group = "androidx.constraintlayout",        name = "constraintlayout",            version.ref = "constraintlayout" }
lifecycle-viewmodel     = { group = "androidx.lifecycle",               name = "lifecycle-viewmodel-ktx",     version.ref = "lifecycleVersion" }
lifecycle-runtime       = { group = "androidx.lifecycle",               name = "lifecycle-runtime-ktx",       version.ref = "lifecycleVersion" }
lifecycle-service       = { group = "androidx.lifecycle",               name = "lifecycle-service",           version.ref = "lifecycleVersion" }
room-runtime            = { group = "androidx.room",                    name = "room-runtime",                version.ref = "room" }
room-ktx                = { group = "androidx.room",                    name = "room-ktx",                    version.ref = "room" }
room-compiler           = { group = "androidx.room",                    name = "room-compiler",               version.ref = "room" }
coroutines-android      = { group = "org.jetbrains.kotlinx",            name = "kotlinx-coroutines-android",  version.ref = "coroutines" }
navigation-fragment     = { group = "androidx.navigation",              name = "navigation-fragment-ktx",     version.ref = "navigation" }
navigation-ui           = { group = "androidx.navigation",              name = "navigation-ui-ktx",           version.ref = "navigation" }
workmanager             = { group = "androidx.work",                    name = "work-runtime-ktx",            version.ref = "workmanager" }
datastore-preferences   = { group = "androidx.datastore",               name = "datastore-preferences",       version.ref = "datastore" }
gson                    = { group = "com.google.code.gson",             name = "gson",                        version.ref = "gson" }
junit                   = { group = "junit",                            name = "junit",                       version.ref = "junit" }
androidx-junit          = { group = "androidx.test.ext",                name = "junit",                       version.ref = "androidxJunit" }
espresso-core           = { group = "androidx.test.espresso",           name = "espresso-core",               version.ref = "espresso" }

[plugins]
android-application = { id = "com.android.application",        version.ref = "agp" }
kotlin-android      = { id = "org.jetbrains.kotlin.android",   version.ref = "kotlin" }
ksp                 = { id = "com.google.devtools.ksp",         version.ref = "ksp" }
